### ISSUE TITLE
compiler failed on ms vc++ 2019

### ISSUE THREAD

**Issue by ktprime** [1ykos/wmath#1]
patchmap crashed or failed(hanged) to pass my hash test.

the test code as follow.
https://github.com/ktprime/emhash/blob/master/bench/fbench.cpp

**Comment by 1ykos** [comment]
thank you, I'll have a look.

Am Sa., 29. Aug. 2020 um 07:51 Uhr schrieb hyb <notifications@github.com>:

**Comment by 1ykos** [comment]
How do I compile the benchmark?
I tried compiling fbench.cpp directly but then I need to specify many
includes. And I tried:
mkdir ~/bin/emhash
cd ~/bin/emhash
cmake ~/src/emhash
make
Scanning dependencies of target hbench
[ 16%] Building CXX object CMakeFiles/hbench.dir/bench/hbench.cpp.o
/home/usr/src/emhash/bench/hbench.cpp:5:10: fatal error: martin/robin_hood.h:
No such file or directory
   5 | #include "martin/robin_hood.h"
     |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/hbench.dir/build.make:82:
CMakeFiles/hbench.dir/bench/hbench.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:99: CMakeFiles/hbench.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

Am Mo., 31. Aug. 2020 um 01:20 Uhr schrieb Wolfgang Brehm <
wolfgang.brehm@gmail.com>:

**Comment by 1ykos** [comment]
Managed to compile. The only problem is the hash function being used, the identity function is not [a good hash function](https://stackoverflow.com/a/57556517/2119377), try this for example:
``` diff
diff --git a/bench/fbench.cpp b/bench/fbench.cpp
index fb4724e..84d5cec 100644
--- a/bench/fbench.cpp
+++ b/bench/fbench.cpp
@@ -387,7 +387,14 @@ void test_delay()
 
 struct Hash32 {
     inline size_t operator()(const uint32_t x) const {
-        return x;
+      uint64_t h = x;
+      h*=14486182417589908843ull;
+      h^=h>>32;
+      h*=14486182417589908843ull;
+      h^=h>>32;
+      h*=14486182417589908843ull;
+      h^=h>>32;
+      return h;
     }
 };
```

**Comment by ktprime** [comment]
compiler error:


result_of is not a member of std










At 2020-09-01 17:49:10, "Wolfgang Brehm" <notifications@github.com> wrote:

Managed to compile. The only problem is the hash function being used, the identity function is not (a good hash function)[https://stackoverflow.com/a/57556517/2119377], try this for example:

diff --git a/bench/fbench.cpp b/bench/fbench.cpp
index fb4724e..84d5cec 100644
--- a/bench/fbench.cpp+++ b/bench/fbench.cpp@@ -387,7 +387,14 @@ void test_delay()
 
 struct Hash32 {
     inline size_t operator()(const uint32_t x) const {
-        return x;+      uint64_t h = x;+      h*=14486182417589908843ull;+      h^=h>>32;+      h*=14486182417589908843ull;+      h^=h>>32;+      h*=14486182417589908843ull;+      h^=h>>32;+      return h;
     }
 };

**Comment by 1ykos** [comment]
you need to compile with -std=c++17 to have invoke_result available, result_of was deprecated and I forgot to remove it, but it is fixed now.
The line needs to be:
` 513       typedef typename std::invoke_result<hash,key_type&>::type hash_type;`

**Comment by ktprime** [comment]
huangyuanbing@MacBook-Pro bench % make

g++ -O3 -march=native -mtune=native -fwhole-program -std=c++17 -I.. -I../thirdparty  hbench.cpp -o hbench

clang: warning: optimization flag '-fwhole-program' is not supported [-Wignored-optimization-argument]

In file included from hbench.cpp:12:

../thirdparty/patchmap/patchmap.hpp:395:25: error: implicit instantiation of undefined template 'whash::hash<unsigned long, void>'

                    h = hash<size_t>{}(h);

                        ^

../thirdparty/patchmap/patchmap.hpp:261:11: note: template is declared here

    class hash;

          ^

../thirdparty/patchmap/patchmap.hpp:439:21: error: implicit instantiation of undefined template 'whash::hash<unsigned long, void>'

                    hash<size_t>{}(hash<typename remove_const<decltype(e)>::type>{}(e));

                    ^

../thirdparty/patchmap/patchmap.hpp:261:11: note: template is declared here

    class hash;

          ^

hbench.cpp:325:60: warning: format specifies type 'long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]

    printf("load_factor = %.2lf %ld\n\n", m.load_factor(), ret);

                                ~~~                        ^~~

                                %llu

hbench.cpp:365:62: note: in instantiation of function template specialization 'test<std::__1::unordered_map<unsigned long long, unsigned int, std::__1::hash<long long>, std::__1::equal_to<unsigned long

      long>, std::__1::allocator<std::__1::pair<const unsigned long long, unsigned int> > > >' requested here

    { std::unordered_map<uint64_t, Value, hash_t> m3; ret -= test(m3, "\nstd::unordered_map"); }

**Comment by ktprime** [comment]
I have updated your code and fixed some issiue on vc++ 2019
     https://github.com/ktprime/emhash/blob/master/thirdparty/patchmap/patchmap.hpp
It's also hang for test fbench. 
















At 2020-09-01 20:53:16, "Wolfgang Brehm" <notifications@github.com> wrote:

you need to compile with -std=c++17 to have invoke_result available, result_of was deprecated and I forgot to remove it, but it is fixed now.
The line needs to be:
513 typedef typename std::invoke_result<hash,key_type&>::type hash_type;
